service:
  flush: 1
  log_level: info

pipeline:
  inputs:
    - name: tail
      path: /var/log/syslog
      tag: app
      read_from_head: true

  filters:
    - name: wasm
      match: app
      wasm_path: fluent_bit_matchy-0.2.0.wasm
      function_name: matchy_filter
      accessible_paths: .
      wasm_heap_size: 256M

  outputs:
    - name: stdout
      match: "*"
